sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/test/**,**/.github/**
sonar.tests=test
sonar.test.inclusions=test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
